[username]
# Always show username
# show_always = true

[hostname]
# Always show hostname
# ssh_only = false

[directory]
# Show full directory paths
truncation_length=0

[git_status]
show_sync_count = true
conflicted = " =$count"
ahead = " ⇡$count"
behind = " ⇣$count"
diverged = " ⇕⇡$ahead_count⇣$behind_count"
untracked = " ?$count"
stashed = " $$count"
modified = " !$count"
staged = " +$count"
renamed = " »$count"
deleted = " ✘$count"
format = "[(\\[$all_status \\])]($style)"