[username]
# Always show username
# show_always = true

[hostname]
# Always show hostname
# ssh_only = false

[directory]
# Show full directory paths
truncation_length=0

[git_status]
# Show counts for all status types, with spaces in between theem
conflicted = " =$count"
ahead = " ⇡$count"
behind = " ⇣$count"
diverged = " ⇕⇡$ahead_count⇣$behind_count"
untracked = " ?$count"
stashed = " $$count"
modified = " !$count"
staged = " +$count"
renamed = " »$count"
deleted = " ✘$count"
format = "[(\\[$all_status \\][ ](none))]($style)"

[[battery.display]]
# Set a higher threshold for battery status
threshold = 25

[git_metrics]
# See number of lines changed across all tracked/untracked files since last commit in git repo
disabled = false
