[directory]
truncation_length = 0 # Show full directory paths

[git_metrics]
disabled = false # See number of lines changed across all tracked/untracked files since last commit

# Show counts for all status types
[git_status]
conflicted = " =$count"
ahead = " ⇡$count"
behind = " ⇣$count"
diverged = " ⇕ ⇡$ahead_count ⇣$behind_count"
untracked = " ?$count"
stashed = " \\$$count"
modified = " !$count"
staged = " +$count"
renamed = " »$count"
deleted = " ✘$count"
format = "([\\[$ahead_behind$conflicted$stashed$untracked[$staged$renamed](bold green)[$modified](bold yellow)[$deleted](bold red) \\]](bold bright-black) )"

[battery]
disabled = true

# Turn off project packaging information
[package]
disabled = true

# Turn off language/tooling information
[aws]
disabled = true
[bun]
disabled = true
[c]
disabled = true
[cmake]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[daml]
disabled = true
[deno]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[golang]
disabled = true
[guix_shell]
disabled = true
[haskell]
disabled = true
[haxe]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[lua]
disabled = true
[meson]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[opa]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[raku]
disabled = true
[red]
disabled = true
[rlang]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[solidity]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[typst]
disabled = true
[vagrant]
disabled = true
[vlang]
disabled = true
[zig]
disabled = true
